using gip.core.autocomponent;
using gip.core.datamodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace kse.mes.processapplication
{
	[DataContract]
	[ACSerializeableInfo]
	[ACClassInfo(Const.PackName_VarioAutomation, "en{'AlarmPositioning'}de{'AlarmPositioning'}", Global.ACKinds.TACClass, Global.ACStorableTypes.NotStorable, true, false)]
	[ACPropertyEntity(100, "Bit08", "en{'Alarm stirring device 17'}de{'Alarm stirring device 17'}")]
	[ACPropertyEntity(101, "Bit09", "en{'Alarm stirring device 18'}de{'Alarm stirring device 18'}")]
	[ACPropertyEntity(102, "Bit10", "en{'Alarm stirring device 19'}de{'Alarm stirring device 19'}")]
	[ACPropertyEntity(103, "Bit11", "en{'Alarm stirring device 20'}de{'Alarm stirring device 20'}")]
	[ACPropertyEntity(104, "Bit12", "en{'Alarm stirring device 21'}de{'Alarm stirring device 21'}")]
	[ACPropertyEntity(105, "Bit13", "en{'Alarm stirring device 22'}de{'Alarm stirring device 22'}")]
	[ACPropertyEntity(106, "Bit14", "en{'Alarm stirring device 23'}de{'Alarm stirring device 23'}")]
	[ACPropertyEntity(107, "Bit15", "en{'Alarm stirring device 24'}de{'Alarm stirring device 24'}")]
	[ACPropertyEntity(108, "Bit00", "en{'Alarm stirring device 25'}de{'Alarm stirring device 25'}")]
	[ACPropertyEntity(109, "Bit01", "en{'Alarm stirring device 26'}de{'Alarm stirring device 26'}")]
	[ACPropertyEntity(110, "Bit02", "en{'Alarm stirring device 27'}de{'Alarm stirring device 27'}")]
	[ACPropertyEntity(111, "Bit03", "en{'Alarm stirring device 28'}de{'Alarm stirring device 28'}")]
	[ACPropertyEntity(112, "Bit04", "en{'Alarm stirring device 29'}de{'Alarm stirring device 29'}")]
	[ACPropertyEntity(113, "Bit05", "en{'Alarm stirring device 30'}de{'Alarm stirring device 30'}")]
	[ACPropertyEntity(114, "Bit06", "en{'Alarm stirring device 31'}de{'Alarm stirring device 31'}")]
	[ACPropertyEntity(115, "Bit07", "en{'Alarm stirring device 32'}de{'Alarm stirring device 32'}")]
	// @aagincic: AutoGenerated file form AlarmStirringDevices2.csv definition
    public class AlarmStirringDevices2 :  BitAccessForInt16
	{
		#region c'tors
        public AlarmStirringDevices2()
        {
        }

        public AlarmStirringDevices2(IACType acValueType)
            : base(acValueType)
        {
        }
        #endregion

		#region Customized Bits

		 
		public bool Bit00_AlarmStirringDevice25
		{
			get { return Bit00; }
			set { Bit00 = value; }
		}
		 
		public bool Bit01_AlarmStirringDevice26
		{
			get { return Bit01; }
			set { Bit01 = value; }
		}
		 
		public bool Bit02_AlarmStirringDevice27
		{
			get { return Bit02; }
			set { Bit02 = value; }
		}
		 
		public bool Bit03_AlarmStirringDevice28
		{
			get { return Bit03; }
			set { Bit03 = value; }
		}
		 
		public bool Bit04_AlarmStirringDevice29
		{
			get { return Bit04; }
			set { Bit04 = value; }
		}
		 
		public bool Bit05_AlarmStirringDevice30
		{
			get { return Bit05; }
			set { Bit05 = value; }
		}
		 
		public bool Bit06_AlarmStirringDevice31
		{
			get { return Bit06; }
			set { Bit06 = value; }
		}
		 
		public bool Bit07_AlarmStirringDevice32
		{
			get { return Bit07; }
			set { Bit07 = value; }
		}
		 
		public bool Bit08_AlarmStirringDevice17
		{
			get { return Bit08; }
			set { Bit08 = value; }
		}
		 
		public bool Bit09_AlarmStirringDevice18
		{
			get { return Bit09; }
			set { Bit09 = value; }
		}
		 
		public bool Bit10_AlarmStirringDevice19
		{
			get { return Bit10; }
			set { Bit10 = value; }
		}
		 
		public bool Bit11_AlarmStirringDevice20
		{
			get { return Bit11; }
			set { Bit11 = value; }
		}
		 
		public bool Bit12_AlarmStirringDevice21
		{
			get { return Bit12; }
			set { Bit12 = value; }
		}
		 
		public bool Bit13_AlarmStirringDevice22
		{
			get { return Bit13; }
			set { Bit13 = value; }
		}
		 
		public bool Bit14_AlarmStirringDevice23
		{
			get { return Bit14; }
			set { Bit14 = value; }
		}
		 
		public bool Bit15_AlarmStirringDevice24
		{
			get { return Bit15; }
			set { Bit15 = value; }
		}
		
		#endregion
		
	}
}
