using gip.core.autocomponent;
using gip.core.datamodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace kse.mes.processapplication
{
	[DataContract]
	[ACSerializeableInfo]
	[ACClassInfo(Const.PackName_VarioAutomation, "en{'AlarmPositioning'}de{'AlarmPositioning'}", Global.ACKinds.TACClass, Global.ACStorableTypes.NotStorable, true, false)]
	[ACPropertyEntity(100, "Bit08", "en{'Alarm dosing screw 17'}de{'Alarm dosing screw 17'}")]
	[ACPropertyEntity(101, "Bit09", "en{'Alarm dosing screw 18'}de{'Alarm dosing screw 18'}")]
	[ACPropertyEntity(102, "Bit10", "en{'Alarm dosing screw 19'}de{'Alarm dosing screw 19'}")]
	[ACPropertyEntity(103, "Bit11", "en{'Alarm dosing screw 20'}de{'Alarm dosing screw 20'}")]
	[ACPropertyEntity(104, "Bit12", "en{'Alarm dosing screw 21'}de{'Alarm dosing screw 21'}")]
	[ACPropertyEntity(105, "Bit13", "en{'Alarm dosing screw 22'}de{'Alarm dosing screw 22'}")]
	[ACPropertyEntity(106, "Bit14", "en{'Alarm dosing screw 23'}de{'Alarm dosing screw 23'}")]
	[ACPropertyEntity(107, "Bit15", "en{'Alarm dosing screw 24'}de{'Alarm dosing screw 24'}")]
	[ACPropertyEntity(108, "Bit00", "en{'Alarm dosing screw 25'}de{'Alarm dosing screw 25'}")]
	[ACPropertyEntity(109, "Bit01", "en{'Alarm dosing screw 26'}de{'Alarm dosing screw 26'}")]
	[ACPropertyEntity(110, "Bit02", "en{'Alarm dosing screw 27'}de{'Alarm dosing screw 27'}")]
	[ACPropertyEntity(111, "Bit03", "en{'Alarm dosing screw 28'}de{'Alarm dosing screw 28'}")]
	[ACPropertyEntity(112, "Bit04", "en{'Alarm dosing screw 29'}de{'Alarm dosing screw 29'}")]
	[ACPropertyEntity(113, "Bit05", "en{'Alarm dosing screw 30'}de{'Alarm dosing screw 30'}")]
	[ACPropertyEntity(114, "Bit06", "en{'Alarm dosing screw 31'}de{'Alarm dosing screw 31'}")]
	[ACPropertyEntity(115, "Bit07", "en{'Alarm dosing screw 32'}de{'Alarm dosing screw 32'}")]
	// @aagincic: AutoGenerated file form AlarmDosingScrew2.csv definition
    public class AlarmDosingScrew2 :  BitAccessForInt16
	{
		#region c'tors
        public AlarmDosingScrew2()
        {
        }

        public AlarmDosingScrew2(IACType acValueType)
            : base(acValueType)
        {
        }
        #endregion

		#region Customized Bits

		 
		public bool Bit00_AlarmDosingScrew25
		{
			get { return Bit00; }
			set { Bit00 = value; }
		}
		 
		public bool Bit01_AlarmDosingScrew26
		{
			get { return Bit01; }
			set { Bit01 = value; }
		}
		 
		public bool Bit02_AlarmDosingScrew27
		{
			get { return Bit02; }
			set { Bit02 = value; }
		}
		 
		public bool Bit03_AlarmDosingScrew28
		{
			get { return Bit03; }
			set { Bit03 = value; }
		}
		 
		public bool Bit04_AlarmDosingScrew29
		{
			get { return Bit04; }
			set { Bit04 = value; }
		}
		 
		public bool Bit05_AlarmDosingScrew30
		{
			get { return Bit05; }
			set { Bit05 = value; }
		}
		 
		public bool Bit06_AlarmDosingScrew31
		{
			get { return Bit06; }
			set { Bit06 = value; }
		}
		 
		public bool Bit07_AlarmDosingScrew32
		{
			get { return Bit07; }
			set { Bit07 = value; }
		}
		 
		public bool Bit08_AlarmDosingScrew17
		{
			get { return Bit08; }
			set { Bit08 = value; }
		}
		 
		public bool Bit09_AlarmDosingScrew18
		{
			get { return Bit09; }
			set { Bit09 = value; }
		}
		 
		public bool Bit10_AlarmDosingScrew19
		{
			get { return Bit10; }
			set { Bit10 = value; }
		}
		 
		public bool Bit11_AlarmDosingScrew20
		{
			get { return Bit11; }
			set { Bit11 = value; }
		}
		 
		public bool Bit12_AlarmDosingScrew21
		{
			get { return Bit12; }
			set { Bit12 = value; }
		}
		 
		public bool Bit13_AlarmDosingScrew22
		{
			get { return Bit13; }
			set { Bit13 = value; }
		}
		 
		public bool Bit14_AlarmDosingScrew23
		{
			get { return Bit14; }
			set { Bit14 = value; }
		}
		 
		public bool Bit15_AlarmDosingScrew24
		{
			get { return Bit15; }
			set { Bit15 = value; }
		}
		
		#endregion
		
	}
}
