using gip.core.autocomponent;
using gip.core.datamodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace kse.mes.processapplication
{
	[DataContract]
	[ACSerializeableInfo]
	[ACClassInfo(Const.PackName_VarioAutomation, "en{'AlarmPositioning'}de{'AlarmPositioning'}", Global.ACKinds.TACClass, Global.ACStorableTypes.NotStorable, true, false)]
	[ACPropertyEntity(100, "Bit08", "en{'Wrong silo open during dosing / discharging: silo 17'}de{'Wrong silo open during dosing / discharging: silo 17'}")]
	[ACPropertyEntity(101, "Bit09", "en{'Wrong silo open during dosing / discharging: silo 18'}de{'Wrong silo open during dosing / discharging: silo 18'}")]
	[ACPropertyEntity(102, "Bit10", "en{'Wrong silo open during dosing / discharging: silo 19'}de{'Wrong silo open during dosing / discharging: silo 19'}")]
	[ACPropertyEntity(103, "Bit11", "en{'Wrong silo open during dosing / discharging: silo 20'}de{'Wrong silo open during dosing / discharging: silo 20'}")]
	[ACPropertyEntity(104, "Bit12", "en{'Wrong silo open during dosing / discharging: silo 21'}de{'Wrong silo open during dosing / discharging: silo 21'}")]
	[ACPropertyEntity(105, "Bit13", "en{'Wrong silo open during dosing / discharging: silo 22'}de{'Wrong silo open during dosing / discharging: silo 22'}")]
	[ACPropertyEntity(106, "Bit14", "en{'Wrong silo open during dosing / discharging: silo 23'}de{'Wrong silo open during dosing / discharging: silo 23'}")]
	[ACPropertyEntity(107, "Bit15", "en{'Wrong silo open during dosing / discharging: silo 24'}de{'Wrong silo open during dosing / discharging: silo 24'}")]
	[ACPropertyEntity(108, "Bit00", "en{'Wrong silo open during dosing / discharging: silo 25'}de{'Wrong silo open during dosing / discharging: silo 25'}")]
	[ACPropertyEntity(109, "Bit01", "en{'Wrong silo open during dosing / discharging: silo 26'}de{'Wrong silo open during dosing / discharging: silo 26'}")]
	[ACPropertyEntity(110, "Bit02", "en{'Wrong silo open during dosing / discharging: silo 27'}de{'Wrong silo open during dosing / discharging: silo 27'}")]
	[ACPropertyEntity(111, "Bit03", "en{'Wrong silo open during dosing / discharging: silo 28'}de{'Wrong silo open during dosing / discharging: silo 28'}")]
	[ACPropertyEntity(112, "Bit04", "en{'Wrong silo open during dosing / discharging: silo 29'}de{'Wrong silo open during dosing / discharging: silo 29'}")]
	[ACPropertyEntity(113, "Bit05", "en{'Wrong silo open during dosing / discharging: silo 30'}de{'Wrong silo open during dosing / discharging: silo 30'}")]
	[ACPropertyEntity(114, "Bit06", "en{'Wrong silo open during dosing / discharging: silo 31'}de{'Wrong silo open during dosing / discharging: silo 31'}")]
	[ACPropertyEntity(115, "Bit07", "en{'Wrong silo open during dosing / discharging: silo 32'}de{'Wrong silo open during dosing / discharging: silo 32'}")]
	// @aagincic: AutoGenerated file form AlarmDosingSlides2.csv definition
    public class AlarmDosingSlides2 :  BitAccessForInt16
	{
		#region c'tors
        public AlarmDosingSlides2()
        {
        }

        public AlarmDosingSlides2(IACType acValueType)
            : base(acValueType)
        {
        }
        #endregion

		#region Customized Bits

		 
		public bool Bit00_WrongSiloOpenDuringDosingDischargingSilo25
		{
			get { return Bit00; }
			set { Bit00 = value; }
		}
		 
		public bool Bit01_WrongSiloOpenDuringDosingDischargingSilo26
		{
			get { return Bit01; }
			set { Bit01 = value; }
		}
		 
		public bool Bit02_WrongSiloOpenDuringDosingDischargingSilo27
		{
			get { return Bit02; }
			set { Bit02 = value; }
		}
		 
		public bool Bit03_WrongSiloOpenDuringDosingDischargingSilo28
		{
			get { return Bit03; }
			set { Bit03 = value; }
		}
		 
		public bool Bit04_WrongSiloOpenDuringDosingDischargingSilo29
		{
			get { return Bit04; }
			set { Bit04 = value; }
		}
		 
		public bool Bit05_WrongSiloOpenDuringDosingDischargingSilo30
		{
			get { return Bit05; }
			set { Bit05 = value; }
		}
		 
		public bool Bit06_WrongSiloOpenDuringDosingDischargingSilo31
		{
			get { return Bit06; }
			set { Bit06 = value; }
		}
		 
		public bool Bit07_WrongSiloOpenDuringDosingDischargingSilo32
		{
			get { return Bit07; }
			set { Bit07 = value; }
		}
		 
		public bool Bit08_WrongSiloOpenDuringDosingDischargingSilo17
		{
			get { return Bit08; }
			set { Bit08 = value; }
		}
		 
		public bool Bit09_WrongSiloOpenDuringDosingDischargingSilo18
		{
			get { return Bit09; }
			set { Bit09 = value; }
		}
		 
		public bool Bit10_WrongSiloOpenDuringDosingDischargingSilo19
		{
			get { return Bit10; }
			set { Bit10 = value; }
		}
		 
		public bool Bit11_WrongSiloOpenDuringDosingDischargingSilo20
		{
			get { return Bit11; }
			set { Bit11 = value; }
		}
		 
		public bool Bit12_WrongSiloOpenDuringDosingDischargingSilo21
		{
			get { return Bit12; }
			set { Bit12 = value; }
		}
		 
		public bool Bit13_WrongSiloOpenDuringDosingDischargingSilo22
		{
			get { return Bit13; }
			set { Bit13 = value; }
		}
		 
		public bool Bit14_WrongSiloOpenDuringDosingDischargingSilo23
		{
			get { return Bit14; }
			set { Bit14 = value; }
		}
		 
		public bool Bit15_WrongSiloOpenDuringDosingDischargingSilo24
		{
			get { return Bit15; }
			set { Bit15 = value; }
		}
		
		#endregion
		
	}
}
