using gip.core.autocomponent;
using gip.core.datamodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace kse.mes.processapplication
{
	[DataContract]
	[ACSerializeableInfo]
	[ACClassInfo(Const.PackName_VarioAutomation, "en{'AlarmPositioning'}de{'AlarmPositioning'}", Global.ACKinds.TACClass, Global.ACStorableTypes.NotStorable, true, false)]
	[ACPropertyEntity(100, "Bit08", "en{'Alarm stirring device 1'}de{'Alarm stirring device 1'}")]
	[ACPropertyEntity(101, "Bit09", "en{'Alarm stirring device 2'}de{'Alarm stirring device 2'}")]
	[ACPropertyEntity(102, "Bit10", "en{'Alarm stirring device 3'}de{'Alarm stirring device 3'}")]
	[ACPropertyEntity(103, "Bit11", "en{'Alarm stirring device 4'}de{'Alarm stirring device 4'}")]
	[ACPropertyEntity(104, "Bit12", "en{'Alarm stirring device 5'}de{'Alarm stirring device 5'}")]
	[ACPropertyEntity(105, "Bit13", "en{'Alarm stirring device 6'}de{'Alarm stirring device 6'}")]
	[ACPropertyEntity(106, "Bit14", "en{'Alarm stirring device 7'}de{'Alarm stirring device 7'}")]
	[ACPropertyEntity(107, "Bit15", "en{'Alarm stirring device 8'}de{'Alarm stirring device 8'}")]
	[ACPropertyEntity(108, "Bit00", "en{'Alarm stirring device 9'}de{'Alarm stirring device 9'}")]
	[ACPropertyEntity(109, "Bit01", "en{'Alarm stirring device 10'}de{'Alarm stirring device 10'}")]
	[ACPropertyEntity(110, "Bit02", "en{'Alarm stirring device 11'}de{'Alarm stirring device 11'}")]
	[ACPropertyEntity(111, "Bit03", "en{'Alarm stirring device 12'}de{'Alarm stirring device 12'}")]
	[ACPropertyEntity(112, "Bit04", "en{'Alarm stirring device 13'}de{'Alarm stirring device 13'}")]
	[ACPropertyEntity(113, "Bit05", "en{'Alarm stirring device 14'}de{'Alarm stirring device 14'}")]
	[ACPropertyEntity(114, "Bit06", "en{'Alarm stirring device 15'}de{'Alarm stirring device 15'}")]
	[ACPropertyEntity(115, "Bit07", "en{'Alarm stirring device 16'}de{'Alarm stirring device 16'}")]
	// @aagincic: AutoGenerated file form AlarmStirringDevices1.csv definition
    public class AlarmStirringDevices1 :  BitAccessForInt16
	{
		#region c'tors
        public AlarmStirringDevices1()
        {
        }

        public AlarmStirringDevices1(IACType acValueType)
            : base(acValueType)
        {
        }
        #endregion

		#region Customized Bits

		 
		public bool Bit00_AlarmStirringDevice9
		{
			get { return Bit00; }
			set { Bit00 = value; }
		}
		 
		public bool Bit01_AlarmStirringDevice10
		{
			get { return Bit01; }
			set { Bit01 = value; }
		}
		 
		public bool Bit02_AlarmStirringDevice11
		{
			get { return Bit02; }
			set { Bit02 = value; }
		}
		 
		public bool Bit03_AlarmStirringDevice12
		{
			get { return Bit03; }
			set { Bit03 = value; }
		}
		 
		public bool Bit04_AlarmStirringDevice13
		{
			get { return Bit04; }
			set { Bit04 = value; }
		}
		 
		public bool Bit05_AlarmStirringDevice14
		{
			get { return Bit05; }
			set { Bit05 = value; }
		}
		 
		public bool Bit06_AlarmStirringDevice15
		{
			get { return Bit06; }
			set { Bit06 = value; }
		}
		 
		public bool Bit07_AlarmStirringDevice16
		{
			get { return Bit07; }
			set { Bit07 = value; }
		}
		 
		public bool Bit08_AlarmStirringDevice1
		{
			get { return Bit08; }
			set { Bit08 = value; }
		}
		 
		public bool Bit09_AlarmStirringDevice2
		{
			get { return Bit09; }
			set { Bit09 = value; }
		}
		 
		public bool Bit10_AlarmStirringDevice3
		{
			get { return Bit10; }
			set { Bit10 = value; }
		}
		 
		public bool Bit11_AlarmStirringDevice4
		{
			get { return Bit11; }
			set { Bit11 = value; }
		}
		 
		public bool Bit12_AlarmStirringDevice5
		{
			get { return Bit12; }
			set { Bit12 = value; }
		}
		 
		public bool Bit13_AlarmStirringDevice6
		{
			get { return Bit13; }
			set { Bit13 = value; }
		}
		 
		public bool Bit14_AlarmStirringDevice7
		{
			get { return Bit14; }
			set { Bit14 = value; }
		}
		 
		public bool Bit15_AlarmStirringDevice8
		{
			get { return Bit15; }
			set { Bit15 = value; }
		}
		
		#endregion
		
	}
}
