using gip.core.autocomponent;
using gip.core.datamodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace kse.mes.processapplication
{
	[DataContract]
	[ACSerializeableInfo]
	[ACClassInfo(Const.PackName_VarioAutomation, "en{'AlarmPositioning'}de{'AlarmPositioning'}", Global.ACKinds.TACClass, Global.ACStorableTypes.NotStorable, true, false)]
	[ACPropertyEntity(100, "Bit08", "en{'Alarm processor loads'}de{'Alarm processor loads'}")]
	[ACPropertyEntity(101, "Bit09", "en{'Emergency stop not ok'}de{'Emergency stop not ok'}")]
	[ACPropertyEntity(102, "Bit10", "en{'No communicationo Slave 15: IO'}de{'No communicationo Slave 15: IO'}")]
	[ACPropertyEntity(103, "Bit11", "en{'No communicationo Slave 16: IO'}de{'No communicationo Slave 16: IO'}")]
	[ACPropertyEntity(104, "Bit12", "en{'No communicationo Slave 17: IO'}de{'No communicationo Slave 17: IO'}")]
	[ACPropertyEntity(105, "Bit13", "en{'No communicationo Slave 18: IO'}de{'No communicationo Slave 18: IO'}")]
	[ACPropertyEntity(106, "Bit14", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(107, "Bit15", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(108, "Bit00", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(109, "Bit01", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(110, "Bit02", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(111, "Bit03", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(112, "Bit04", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(113, "Bit05", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(114, "Bit06", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(115, "Bit07", "en{'Not used'}de{'Not used'}")]
	// @aagincic: AutoGenerated file form AlarmGeneral2.csv definition
    public class AlarmGeneral2 :  BitAccessForInt16
	{
		#region c'tors
        public AlarmGeneral2()
        {
        }

        public AlarmGeneral2(IACType acValueType)
            : base(acValueType)
        {
        }
        #endregion

		#region Customized Bits

		 
		public bool Bit00_NotUsed
		{
			get { return Bit00; }
			set { Bit00 = value; }
		}
		 
		public bool Bit01_NotUsed
		{
			get { return Bit01; }
			set { Bit01 = value; }
		}
		 
		public bool Bit02_NotUsed
		{
			get { return Bit02; }
			set { Bit02 = value; }
		}
		 
		public bool Bit03_NotUsed
		{
			get { return Bit03; }
			set { Bit03 = value; }
		}
		 
		public bool Bit04_NotUsed
		{
			get { return Bit04; }
			set { Bit04 = value; }
		}
		 
		public bool Bit05_NotUsed
		{
			get { return Bit05; }
			set { Bit05 = value; }
		}
		 
		public bool Bit06_NotUsed
		{
			get { return Bit06; }
			set { Bit06 = value; }
		}
		 
		public bool Bit07_NotUsed
		{
			get { return Bit07; }
			set { Bit07 = value; }
		}
		 
		public bool Bit08_AlarmProcessorLoads
		{
			get { return Bit08; }
			set { Bit08 = value; }
		}
		 
		public bool Bit09_EmergencyStopNotOk
		{
			get { return Bit09; }
			set { Bit09 = value; }
		}
		 
		public bool Bit10_NoCommunicationoSlave15Io
		{
			get { return Bit10; }
			set { Bit10 = value; }
		}
		 
		public bool Bit11_NoCommunicationoSlave16Io
		{
			get { return Bit11; }
			set { Bit11 = value; }
		}
		 
		public bool Bit12_NoCommunicationoSlave17Io
		{
			get { return Bit12; }
			set { Bit12 = value; }
		}
		 
		public bool Bit13_NoCommunicationoSlave18Io
		{
			get { return Bit13; }
			set { Bit13 = value; }
		}
		 
		public bool Bit14_NotUsed
		{
			get { return Bit14; }
			set { Bit14 = value; }
		}
		 
		public bool Bit15_NotUsed
		{
			get { return Bit15; }
			set { Bit15 = value; }
		}
		
		#endregion
		
	}
}
