using gip.core.autocomponent;
using gip.core.datamodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace kse.mes.processapplication
{
	[DataContract]
	[ACSerializeableInfo]
	[ACClassInfo(Const.PackName_VarioAutomation, "en{'AlarmPositioning'}de{'AlarmPositioning'}", Global.ACKinds.TACClass, Global.ACStorableTypes.NotStorable, true, false)]
	[ACPropertyEntity(100, "Bit08", "en{'Wrong silo open during dosing / discharging: silo 1'}de{'Wrong silo open during dosing / discharging: silo 1'}")]
	[ACPropertyEntity(101, "Bit09", "en{'Wrong silo open during dosing / discharging: silo 2'}de{'Wrong silo open during dosing / discharging: silo 2'}")]
	[ACPropertyEntity(102, "Bit10", "en{'Wrong silo open during dosing / discharging: silo 3'}de{'Wrong silo open during dosing / discharging: silo 3'}")]
	[ACPropertyEntity(103, "Bit11", "en{'Wrong silo open during dosing / discharging: silo 4'}de{'Wrong silo open during dosing / discharging: silo 4'}")]
	[ACPropertyEntity(104, "Bit12", "en{'Wrong silo open during dosing / discharging: silo 5'}de{'Wrong silo open during dosing / discharging: silo 5'}")]
	[ACPropertyEntity(105, "Bit13", "en{'Wrong silo open during dosing / discharging: silo 6'}de{'Wrong silo open during dosing / discharging: silo 6'}")]
	[ACPropertyEntity(106, "Bit14", "en{'Wrong silo open during dosing / discharging: silo 7'}de{'Wrong silo open during dosing / discharging: silo 7'}")]
	[ACPropertyEntity(107, "Bit15", "en{'Wrong silo open during dosing / discharging: silo 8'}de{'Wrong silo open during dosing / discharging: silo 8'}")]
	[ACPropertyEntity(108, "Bit00", "en{'Wrong silo open during dosing / discharging: silo 9'}de{'Wrong silo open during dosing / discharging: silo 9'}")]
	[ACPropertyEntity(109, "Bit01", "en{'Wrong silo open during dosing / discharging: silo 10'}de{'Wrong silo open during dosing / discharging: silo 10'}")]
	[ACPropertyEntity(110, "Bit02", "en{'Wrong silo open during dosing / discharging: silo 11'}de{'Wrong silo open during dosing / discharging: silo 11'}")]
	[ACPropertyEntity(111, "Bit03", "en{'Wrong silo open during dosing / discharging: silo 12'}de{'Wrong silo open during dosing / discharging: silo 12'}")]
	[ACPropertyEntity(112, "Bit04", "en{'Wrong silo open during dosing / discharging: silo 13'}de{'Wrong silo open during dosing / discharging: silo 13'}")]
	[ACPropertyEntity(113, "Bit05", "en{'Wrong silo open during dosing / discharging: silo 14'}de{'Wrong silo open during dosing / discharging: silo 14'}")]
	[ACPropertyEntity(114, "Bit06", "en{'Wrong silo open during dosing / discharging: silo 15'}de{'Wrong silo open during dosing / discharging: silo 15'}")]
	[ACPropertyEntity(115, "Bit07", "en{'Wrong silo open during dosing / discharging: silo 16'}de{'Wrong silo open during dosing / discharging: silo 16'}")]
	// @aagincic: AutoGenerated file form AlarmDosingSlides1.csv definition
    public class AlarmDosingSlides1 :  BitAccessForInt16
	{
		#region c'tors
        public AlarmDosingSlides1()
        {
        }

        public AlarmDosingSlides1(IACType acValueType)
            : base(acValueType)
        {
        }
        #endregion

		#region Customized Bits

		 
		public bool Bit00_WrongSiloOpenDuringDosingDischargingSilo9
		{
			get { return Bit00; }
			set { Bit00 = value; }
		}
		 
		public bool Bit01_WrongSiloOpenDuringDosingDischargingSilo10
		{
			get { return Bit01; }
			set { Bit01 = value; }
		}
		 
		public bool Bit02_WrongSiloOpenDuringDosingDischargingSilo11
		{
			get { return Bit02; }
			set { Bit02 = value; }
		}
		 
		public bool Bit03_WrongSiloOpenDuringDosingDischargingSilo12
		{
			get { return Bit03; }
			set { Bit03 = value; }
		}
		 
		public bool Bit04_WrongSiloOpenDuringDosingDischargingSilo13
		{
			get { return Bit04; }
			set { Bit04 = value; }
		}
		 
		public bool Bit05_WrongSiloOpenDuringDosingDischargingSilo14
		{
			get { return Bit05; }
			set { Bit05 = value; }
		}
		 
		public bool Bit06_WrongSiloOpenDuringDosingDischargingSilo15
		{
			get { return Bit06; }
			set { Bit06 = value; }
		}
		 
		public bool Bit07_WrongSiloOpenDuringDosingDischargingSilo16
		{
			get { return Bit07; }
			set { Bit07 = value; }
		}
		 
		public bool Bit08_WrongSiloOpenDuringDosingDischargingSilo1
		{
			get { return Bit08; }
			set { Bit08 = value; }
		}
		 
		public bool Bit09_WrongSiloOpenDuringDosingDischargingSilo2
		{
			get { return Bit09; }
			set { Bit09 = value; }
		}
		 
		public bool Bit10_WrongSiloOpenDuringDosingDischargingSilo3
		{
			get { return Bit10; }
			set { Bit10 = value; }
		}
		 
		public bool Bit11_WrongSiloOpenDuringDosingDischargingSilo4
		{
			get { return Bit11; }
			set { Bit11 = value; }
		}
		 
		public bool Bit12_WrongSiloOpenDuringDosingDischargingSilo5
		{
			get { return Bit12; }
			set { Bit12 = value; }
		}
		 
		public bool Bit13_WrongSiloOpenDuringDosingDischargingSilo6
		{
			get { return Bit13; }
			set { Bit13 = value; }
		}
		 
		public bool Bit14_WrongSiloOpenDuringDosingDischargingSilo7
		{
			get { return Bit14; }
			set { Bit14 = value; }
		}
		 
		public bool Bit15_WrongSiloOpenDuringDosingDischargingSilo8
		{
			get { return Bit15; }
			set { Bit15 = value; }
		}
		
		#endregion
		
	}
}
