using gip.core.autocomponent;
using gip.core.datamodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace kse.mes.processapplication
{
	[DataContract]
	[ACSerializeableInfo]
	[ACClassInfo(Const.PackName_VarioAutomation, "en{'AlarmPositioning'}de{'AlarmPositioning'}", Global.ACKinds.TACClass, Global.ACStorableTypes.NotStorable, true, false)]
	[ACPropertyEntity(100, "Bit08", "en{'Warning: No air pressure'}de{'Warning: No air pressure'}")]
	[ACPropertyEntity(101, "Bit09", "en{'UPS alarm'}de{'UPS alarm'}")]
	[ACPropertyEntity(102, "Bit10", "en{'No communication Slave 11: IO'}de{'No communication Slave 11: IO'}")]
	[ACPropertyEntity(103, "Bit11", "en{'No communication Slave 12: IO'}de{'No communication Slave 12: IO'}")]
	[ACPropertyEntity(104, "Bit12", "en{'No communication Slave 13: IO'}de{'No communication Slave 13: IO'}")]
	[ACPropertyEntity(105, "Bit13", "en{'No communication Slave 14: IO'}de{'No communication Slave 14: IO'}")]
	[ACPropertyEntity(106, "Bit14", "en{'No communication Slave 90: Weight signal'}de{'No communication Slave 90: Weight signal'}")]
	[ACPropertyEntity(107, "Bit15", "en{'No communication Slave 95: frequency controller ventilator'}de{'No communication Slave 95: frequency controller ventilator'}")]
	[ACPropertyEntity(108, "Bit00", "en{'No communication Slave 96: frequency controller positioning X'}de{'No communication Slave 96: frequency controller positioning X'}")]
	[ACPropertyEntity(109, "Bit01", "en{'No communication Slave 97: frequency controller positioning Y'}de{'No communication Slave 97: frequency controller positioning Y'}")]
	[ACPropertyEntity(110, "Bit02", "en{'No communication Slave 98: frequency controller screws'}de{'No communication Slave 98: frequency controller screws'}")]
	[ACPropertyEntity(111, "Bit03", "en{'Warning disk space C'}de{'Warning disk space C'}")]
	[ACPropertyEntity(112, "Bit04", "en{'Alarm disk space C'}de{'Alarm disk space C'}")]
	[ACPropertyEntity(113, "Bit05", "en{'Alarm memory'}de{'Alarm memory'}")]
	[ACPropertyEntity(114, "Bit06", "en{'Warning CPU temperature'}de{'Warning CPU temperature'}")]
	[ACPropertyEntity(115, "Bit07", "en{'Alarm CPU temperature'}de{'Alarm CPU temperature'}")]
	// @aagincic: AutoGenerated file form AlarmGeneral1.csv definition
    public class AlarmGeneral1 :  BitAccessForInt16
	{
		#region c'tors
        public AlarmGeneral1()
        {
        }

        public AlarmGeneral1(IACType acValueType)
            : base(acValueType)
        {
        }
        #endregion

		#region Customized Bits

		 
		public bool Bit00_NoCommunicationSlave96FrequencyControllerPositioningX
		{
			get { return Bit00; }
			set { Bit00 = value; }
		}
		 
		public bool Bit01_NoCommunicationSlave97FrequencyControllerPositioningY
		{
			get { return Bit01; }
			set { Bit01 = value; }
		}
		 
		public bool Bit02_NoCommunicationSlave98FrequencyControllerScrews
		{
			get { return Bit02; }
			set { Bit02 = value; }
		}
		 
		public bool Bit03_WarningDiskSpaceC
		{
			get { return Bit03; }
			set { Bit03 = value; }
		}
		 
		public bool Bit04_AlarmDiskSpaceC
		{
			get { return Bit04; }
			set { Bit04 = value; }
		}
		 
		public bool Bit05_AlarmMemory
		{
			get { return Bit05; }
			set { Bit05 = value; }
		}
		 
		public bool Bit06_WarningCpuTemperature
		{
			get { return Bit06; }
			set { Bit06 = value; }
		}
		 
		public bool Bit07_AlarmCpuTemperature
		{
			get { return Bit07; }
			set { Bit07 = value; }
		}
		 
		public bool Bit08_WarningNoAirPressure
		{
			get { return Bit08; }
			set { Bit08 = value; }
		}
		 
		public bool Bit09_UpsAlarm
		{
			get { return Bit09; }
			set { Bit09 = value; }
		}
		 
		public bool Bit10_NoCommunicationSlave11Io
		{
			get { return Bit10; }
			set { Bit10 = value; }
		}
		 
		public bool Bit11_NoCommunicationSlave12Io
		{
			get { return Bit11; }
			set { Bit11 = value; }
		}
		 
		public bool Bit12_NoCommunicationSlave13Io
		{
			get { return Bit12; }
			set { Bit12 = value; }
		}
		 
		public bool Bit13_NoCommunicationSlave14Io
		{
			get { return Bit13; }
			set { Bit13 = value; }
		}
		 
		public bool Bit14_NoCommunicationSlave90WeightSignal
		{
			get { return Bit14; }
			set { Bit14 = value; }
		}
		 
		public bool Bit15_NoCommunicationSlave95FrequencyControllerVentilator
		{
			get { return Bit15; }
			set { Bit15 = value; }
		}
		
		#endregion
		
	}
}
