using gip.core.autocomponent;
using gip.core.datamodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace kse.mes.processapplication
{
	[DataContract]
	[ACSerializeableInfo]
	[ACClassInfo(Const.PackName_VarioAutomation, "en{'AlarmPositioning'}de{'AlarmPositioning'}", Global.ACKinds.TACClass, Global.ACStorableTypes.NotStorable, true, false)]
	[ACPropertyEntity(100, "Bit08", "en{'Alarm WMS A broken wire'}de{'Alarm WMS A broken wire'}")]
	[ACPropertyEntity(101, "Bit09", "en{'Alarm WMS A calibration not OK'}de{'Alarm WMS A calibration not OK'}")]
	[ACPropertyEntity(102, "Bit10", "en{'Alarm WMS A calibration on'}de{'Alarm WMS A calibration on'}")]
	[ACPropertyEntity(103, "Bit11", "en{'Alarm WMS A communication not OK'}de{'Alarm WMS A communication not OK'}")]
	[ACPropertyEntity(104, "Bit12", "en{'Hydro unit thermical fault'}de{'Hydro unit thermical fault'}")]
	[ACPropertyEntity(105, "Bit13", "en{'Alarm WMS B broken wire'}de{'Alarm WMS B broken wire'}")]
	[ACPropertyEntity(106, "Bit14", "en{'Alarm WMS B calibration not OK'}de{'Alarm WMS B calibration not OK'}")]
	[ACPropertyEntity(107, "Bit15", "en{'Alarm WMS B calibration on'}de{'Alarm WMS B calibration on'}")]
	[ACPropertyEntity(108, "Bit00", "en{'Alarm WMS B communication not OK'}de{'Alarm WMS B communication not OK'}")]
	[ACPropertyEntity(109, "Bit01", "en{'Alarm WMS C broken wire'}de{'Alarm WMS C broken wire'}")]
	[ACPropertyEntity(110, "Bit02", "en{'Alarm WMS C calibration not OK'}de{'Alarm WMS C calibration not OK'}")]
	[ACPropertyEntity(111, "Bit03", "en{'Alarm WMS C calibration on'}de{'Alarm WMS C calibration on'}")]
	[ACPropertyEntity(112, "Bit04", "en{'Alarm WMS C communication not OK'}de{'Alarm WMS C communication not OK'}")]
	[ACPropertyEntity(113, "Bit05", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(114, "Bit06", "en{'Not used'}de{'Not used'}")]
	[ACPropertyEntity(115, "Bit07", "en{'Not used'}de{'Not used'}")]
	// @aagincic: AutoGenerated file form AlarmDosingFrame2.csv definition
    public class AlarmDosingFrame2 :  BitAccessForInt16
	{
		#region c'tors
        public AlarmDosingFrame2()
        {
        }

        public AlarmDosingFrame2(IACType acValueType)
            : base(acValueType)
        {
        }
        #endregion

		#region Customized Bits

		 
		public bool Bit00_AlarmWmsBCommunicationNotOk
		{
			get { return Bit00; }
			set { Bit00 = value; }
		}
		 
		public bool Bit01_AlarmWmsCBrokenWire
		{
			get { return Bit01; }
			set { Bit01 = value; }
		}
		 
		public bool Bit02_AlarmWmsCCalibrationNotOk
		{
			get { return Bit02; }
			set { Bit02 = value; }
		}
		 
		public bool Bit03_AlarmWmsCCalibrationOn
		{
			get { return Bit03; }
			set { Bit03 = value; }
		}
		 
		public bool Bit04_AlarmWmsCCommunicationNotOk
		{
			get { return Bit04; }
			set { Bit04 = value; }
		}
		 
		public bool Bit05_NotUsed
		{
			get { return Bit05; }
			set { Bit05 = value; }
		}
		 
		public bool Bit06_NotUsed
		{
			get { return Bit06; }
			set { Bit06 = value; }
		}
		 
		public bool Bit07_NotUsed
		{
			get { return Bit07; }
			set { Bit07 = value; }
		}
		 
		public bool Bit08_AlarmWmsABrokenWire
		{
			get { return Bit08; }
			set { Bit08 = value; }
		}
		 
		public bool Bit09_AlarmWmsACalibrationNotOk
		{
			get { return Bit09; }
			set { Bit09 = value; }
		}
		 
		public bool Bit10_AlarmWmsACalibrationOn
		{
			get { return Bit10; }
			set { Bit10 = value; }
		}
		 
		public bool Bit11_AlarmWmsACommunicationNotOk
		{
			get { return Bit11; }
			set { Bit11 = value; }
		}
		 
		public bool Bit12_HydroUnitThermicalFault
		{
			get { return Bit12; }
			set { Bit12 = value; }
		}
		 
		public bool Bit13_AlarmWmsBBrokenWire
		{
			get { return Bit13; }
			set { Bit13 = value; }
		}
		 
		public bool Bit14_AlarmWmsBCalibrationNotOk
		{
			get { return Bit14; }
			set { Bit14 = value; }
		}
		 
		public bool Bit15_AlarmWmsBCalibrationOn
		{
			get { return Bit15; }
			set { Bit15 = value; }
		}
		
		#endregion
		
	}
}
